services:
  flights:
    image: flights
    container_name: flights
    build: 
      context: ./
      dockerfile: ./containers/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    env_file: 
      - .env
